theme: jekyll-theme-minimal
title: Rudolph Richards
description: Electrical Engineering Student | Circuits & Systems | Creativity, Humanity, Inclusion
logo: assets/images/headshot.jpg

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - assets